### ISSUE TITLE
setup-nox is breaking on linux runners

### ISSUE THREAD

**Issue by henryiii** [excitedleigh/setup-nox#419]
Just today setup-nox 2.0.0 has started breaking on linux runners. I think a `pypy` symlink has been added in a recent PyPy update.

```
Run excitedleigh/setup-nox@v2.0.0

[ '2.7.18', '3.10.4', '3.6.15', '3.7.12', '3.8.12', '3.9.12' ] [ '2.7.18', '3.6.12', '3.7.13', '3.8.13', '3.9.12' ]
/opt/hostedtoolcache/PyPy/2.7.18/x64
internal/fs/utils.js:269
    throw err;
    ^

Error: EEXIST: file already exists, symlink '/opt/hostedtoolcache/PyPy/2.7.18/x64/bin/pypy' -> '/opt/hostedtoolcache/PyPy/2.7.18/x64/bin/pypy2'
    at Object.symlinkSync (fs.js:1095:3)
    at Object.175 (/home/runner/work/_actions/excitedleigh/setup-nox/v2.0.0/dist/index.js:1459:14)
    at __webpack_require__ (/home/runner/work/_actions/excitedleigh/setup-nox/v2.0.0/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/excitedleigh/setup-nox/v2.0.0/dist/index.js:43:19)
    at /home/runner/work/_actions/excitedleigh/setup-nox/v2.0.0/dist/index.js:47:18
    at Object.<anonymous> (/home/runner/work/_actions/excitedleigh/setup-nox/v2.0.0/dist/index.js:50:10)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  errno: -17,
  syscall: 'symlink',
  code: 'EEXIST',
  path: '/opt/hostedtoolcache/PyPy/2.7.18/x64/bin/pypy',
  dest: '/opt/hostedtoolcache/PyPy/2.7.18/x64/bin/pypy2'
}
```

**Comment by henryiii** [comment]
This is an example of a breakage (I'm seeing it in several repos): https://github.com/scikit-hep/particle/runs/5822661207?check_suite_focus=true

**Comment by Randomblock1** [comment]
Can confirm, stopped working after a README update. Same error with PyPy.

**Comment by qorrect** [comment]
Same issue here , `Error: EEXIST: file already exists, symlink '/opt/hostedtoolcache/PyPy/2.7.18/x64/bin/pypy' -> `
